Ext.define('cms.model.wms.wms_OwnerOutorderModel', {
	extend : 'Ext.data.Model',
	fields : [

        {name:'enterpriseNo'},
		{name:'expType'},
		{name:'priority'},
		{name:'deliverObjLevel'},
		{name:'MFlag'},
		{name:'WFlag'},
		{name:'SFlag'},
		{name:'DFlag'},
		{name:'BDivideFlag'},
		{name:'CDivideFlag'},
		{name:'recheckCompute'},
		{name:'sendbufCompute'},
		{name:'commitType'},
		{name:'shortqtyType'},
		{name:'sorterCompute'},
		{name:'batchCompute'},
		{name:'lineFlag'},
		{name:'orderRsv01'},
		{name:'orderRsv02'},
		{name:'orderRsv03'},
		{name:'orderRsv04'},
		{name:'orderRsv05'},
		{name:'orderRsv06'},
		{name:'orderRsv07'},
		{name:'orderRsv08'},
		{name:'rgstName'},
		{name:'rgstDate'},
		{name:'updtName'},
		{name:'updtDate'},
		{name:'abnormalFlag'},
		
		{name:'mflagText'},
		{name:'wflagText'},
		{name:'sflagText'},
		{name:'dflagText'},
		{name:'bdivideflagText'},
		{name:'cdivideflagText'},
		{name:'exptypeText'},
		{name:'strategyId'},
		{name:'strategyName'},
		{name:'betweenTimes'},
		{name:'dropValue'},
		{name:'deliverObjLevelText'},
		{name:'ownerNo'},
		{name:'ownerName'},
		{name:'PFlag'},
		{name:'batchComputeType'},
		{name:'sendComputeLevel'},
		{name:'BWorkFlowFlag'},
		{name:'CWorkFlowFlag'},
		{name:'autodivideflag'},
		{name:'autooutstockflag'}
		
	],
	idProperty : 'expType,enterpriseNo,ownerNo'
});