Ext.define('cms.model.wms.wms_strategyDModel', {
	extend : 'Ext.data.Model',
	fields : [

        {name:'enterpriseNo'},
        {name:'batchStrategyId'},
		{name:'batchRuleId'},
		{name:'batchRuleName'},
		{name:'seqOrder'},
		{name:'status'},
		{name:'batchComputeType'},
		{name:'batchCompute'},
		{name:'taskOrder'},
		{name:'minOrder'},
		{name:'orderSource'},
		{name:'repeatTimes'},
		{name:'deliverType'},
		{name:'deliverAddress'},
		{name:'lineFlag'},
		{name:'shipperNo'},
		{name:'skuLimmit'},
		{name:'waitTimes'},
		{name:'intervalTimes'},
		{name:'CLimmit'},
		{name:'areaLimmit'},
		{name:'itemTypeFlag'},
		{name:'printType'},
		{name:'printEnvoice'},
		{name:'printWaybill'},
		{name:'printPacklist'},
		{name:'custLogiboxRuleId'},
		{name:'divideLogiboxRuleId'},
		{name:'taskRuleId'},
		{name:'rsvControl1'},
		{name:'rsvControl2'},
		{name:'rsvControl3'},
		{name:'rsvControl4'},
		{name:'rsvControl5'},
		{name:'rsvValue1'},
		{name:'rsvValue2'},
		{name:'rsvValue3'},
		{name:'rsvValue4'},
		{name:'rsvValue5'},
		{name:'rgstName'},
		{name:'rgstDate'},
		{name:'updtName'},
		{name:'updtDate'},
		{name:'statusText'},
		{name:'batchComputeTypeText'},
		{name:'batchComputeText'},
		{name:'deliverTypeText'},
		{name:'lineFlagText'},
		{name:'shipperNoText'},
		{name:'CLimmitText'},
		{name:'areaLimmitText'},
		{name:'itemTypeFlagText'},
		{name:'printTypeText'},
		{name:'printEnvoiceText'},
		{name:'printWaybillText'},
		{name:'printPacklistText'},
		{name:'custLogiboxRuleIdText'},
		{name:'taskRuleIdText'},
		{name:'orderSourceText'},
		
		{name:'locateStrategyId'},
		{name:'locateRuleId'},
		{name:'locateRuleName'},
		{name:'deliverObjLevel'},
		{name:'PFlag'},
		{name:'MFlag'},
		{name:'WFlag'},
		{name:'SFlag'},
		{name:'DFlag'},
		{name:'BDivideFlag'},
		{name:'CDivideFlag'},
		{name:'commitType'},
		{name:'shortqtyType'},
		{name:'deliverObjLevelText'},
		{name:'PFlagText'},
		{name:'MFlagText'},
		{name:'WFlagText'},
		{name:'SFlagText'},
		{name:'DFlagText'},
		{name:'BDivideFlagText'},
		{name:'CDivideFlagText'},
		{name:'commitTypeText'},
		{name:'shortqtyTypeText'},
		

		{name:'checkcomputeflagText'},
		{name:'checkcomputelevelText'},
		{name:'checkcomputevalueText'},
		{name:'sendbufcomputeflagText'},
		{name:'sendbufcomputelevelText'},
		{name:'sendbufcomputevalueText'},

		{name:'floworder'},
		{name:'flowvalueText'},
		{name:'flowflagText'},
		
		{name:'ruleId'},
		{name:'ruleName'}
		
		
	],
	idProperty : ''
});