Ext.define('cms.model.cset.cset_AreaBackupDModel',{
	extend:'Ext.data.Model',
	fields:[
	{name:'enterpriseNo'},
	{name:'warehouseNo'},
	{name:'lineId'},
	{name:'wareNo'},
	{name:'areaNo'},
	{name:'stockNo'},
	{name:'ALevel'},
	{name:'keepCells'},
	{name:'mergerFlag'},
	{name:'stockFlag'},
	{name:'floorFlag'},
	{name:'bayFlag'},
	{name:'sortFlag'},
	{name:'stockxFlag'},
	{name:'rgstName'},
	{name:'rgstDate'},
	{name:'updtName'},
	{name:'updtDate'},
	
	{name:'mergerFlagText'},
	{name:'stockFlagText'},
	{name:'floorFlagText'},
	{name:'bayFlagText'},
	{name:'sortFlagText'},
	{name:'stockxFlagText'},
	{name:'wareName'},
	{name:'areaName'}
	]
});