/**
 *库存调账
 *创建：hcx
 */
Ext.define('cms.store.stock.stock_ADjDStore',{
	extend:'Ext.data.Store',
	model:'cms.model.stock.stock_ADjDModel',
	pageSize : appConfig.getPageSize(),
	autoLoad:false,
	proxy:{
		type:'ajax',
		method:'post',
		url:'stock_AdjustAccountsAction_getStockADjDList',
		reader:{
			type:'json',
			root:'rootList',
			totalProperty:'totalCount'
		}
	}
});