Ext.define('cms.model.cdef.cdef_DefStockModel', {
    extend: 'Ext.data.Model',
    fields: [
    	{name:'locno'},
		{name:'wareNo'},
		{name:'wareName'},
		{name:'areaNo'},
		{name:'areaName'},
		{name:'stockNo'},
		{name:'AStockNo'},
		{name:'QStockX'},
		{name:'QBayX'},
		{name:'QStockY'},
		{name:'areaType'},
		{name:'mixFlag'},
		{name:'mixSupplier'},
		{name:'areaPick'},
		{name:'orderType'},
		{name:'stockStatus'},
		{name:'maxQty'},
		{name:'maxWeight'},
		{name:'maxVolume'},
		{name:'limitType'},
		{name:'limitRate'},
		{name:'BPick'},
		{name:'AFlag'},
		{name:'sumCanuseCellno'},
		{name:'usedCell'},
		{name:'pickFlag'},
		{name:'rgstName'},
		{name:'rgstDate'},
		{name:'updtName'},
		{name:'updtDate'},
		{name:'maxCase'},
		
		{name:'areaTypeText'},
		{name:'mixFlagText'},
		{name:'mixSupplierText'},
		{name:'areaPickText'},
		{name:'orderTypeText'},
		{name:'stockStatusText'},
		{name:'limitTypeText'},
		{name:'BPickText'},
		{name:'AFlagText'},
		{name:'pickFlagText'}
    ],
    idProperty:'locno,wareNo,areaNo,stockNo'
});