Ext.define('cms.model.idata.idata_ImPort_DModel', {
    extend: 'Ext.data.Model',
    fields: [			
	   	{name:'importNo'},
		{name:'warehouseNo'},
		{name:'ownerNo'},
		{name:'poId'},
		{name:'poNo'},
		{name:'articleNo'},
		{name:'articleName'},
		{name:'barcode'},
		{name:'spec'},
		{name:'packingSpec'},
		{name:'qminOperatePacking'},//最小操作包装数量
		{name:'unitPacking'},//基本包装数量
		{name:'packingUnit'},
		{name:'packingQty'},
		{name:'poQty'},
		{name:'importQty'},
		{name:'unitCost'},
		{name:'checkName'},
		{name:'status'},
		{name:'checkDate'},
		{name:'outStockFlag'},
		{name:'errorStatus'},
		{name:'itemType'},
		{name:'planAcrossQty'},
		{name:'checkAcrossQty'},
		{name:'qcFlag'},
		
		{name:'planBox'},
		{name:'planDis'},
		{name:'planQmin'},
		
		{name:'custNo'},
		{name:'custName'},
		{name:'ownerArticleNo'},
		{name:'barcode'},
		{name:'inQty'},
		{name:'checkQty'},
		{name:'noCheckQty'},
		{name:'canCheckQty'},
		{name:'poNoAndBarcodeText'},
		{name:'articleText'},
		{name:'articleIdentifier'},
		{name:'printFlag'},
		{name:'produceDateText'},
		{name:'expireDateText'},
		{name:'lotNo'},
		{name:'lotType'},
		{name:'expiryDays'},
		{name:'alarmrate'},
		{name:'freezerate'},
		{name:'checkExcess'},
		{name:'temperatureFlag'},
		{name:'takeType'},
		{name:'qpalette'},
		{name:'qpaletteText'},
		{name:'isDiffConfirmFlag'},//单据是否可以做差异确认(0-不允许;1-允许) huangb 20160721
		{name:'modifyFlag'},//是否可修改允许原单，跨境单重新下单后对原单做调整，0：不允许；1：允许 haungb 20160726
		{name:'importType'}//进货单据类型  haungb 20160726
    ],
    idProperty:'importNo,warehouseNo,ownerNo,poId,poNo'
});