/**
 * 创建人:JUN
 */
Ext.define('cms.model.idata.idata_ImportSdModel', {
    extend: 'Ext.data.Model',
    fields: [
		{name:'SImportNo'},
		{name:'warehouseNo'},
		{name:'ownerNo'},
		{name:'rowId'},
		{name:'articleNo'},
		{name:'packingQty'},
		{name:'poQty'},
		{name:'importQty'},
		{name:'qcQty'},
		{name:'checkName'},
		{name:'status'},
		{name:'checkDate'},
		{name:'qcStatus'},
		{name:'outStockFlag'},
		{name:'outpaceArticleFlag'},
		{name:'itemType'},
		{name:'planAcrossQty'},
		{name:'checkAcrossQty'},
		{name:'qcFlag'},
		
		{name:'importNo'},
		{name:'articleName'},
		{name:'barcode'},
		{name:'produceDate'},
		{name:'expireDate'},
		{name:'lotNo'},
		{name:'pkQty'},
		{name:'checkQty'},
		{name:'expiryDays'},
		{name:'alarmrate'},
		{name:'freezerate'},
		{name:'checkExcess'},
		{name:'noCheckQty'},
		{name:'wareArea'},
		{name:'qualityText'},
		{name:'inQty'},
		{name:'boxPickType'},
		{name:'disPickType'},
		{name:'qpalette'},
		{name:'ownerArticleNo'},
		{name:'lotType'},
		{name:'excessQty'},
		{name:'temperatureFlag'},
		{name:'packingUnit'},//箱包装单位
		{name:'packingUnitQmin'},//中包装单位
		{name:'Unit'},//基本包装单位
		{name:'packingSpec'},//箱包装规格
		{name:'packingSpecQmin'},//中包装规格
		{name:'spec'},//基本包装规格
		{name:'realBox'},//实际箱数
		{name:'realDis'},//实际散数
		{name:'realQmin'},//实际中包数
		{name:'planBox'},//计划箱数
		{name:'planDis'},//计划散数
		{name:'planQmin'},//计划中包数
		{name:'qminOperatePacking'},//最小操作包装数量
		{name:'unitPacking'},//基本包装数量
    ],
    idProperty:'SImportNo,warehouseNo,ownerNo,rowId'
});
