/**
 *下架指示单
 *创建：lich
 */
Ext.define('cms.model.odata.odata_OutstockDirectModel', {
    extend: 'Ext.data.Model',
    fields: [	
	{name:'warehouseNo'},
	{name:'directSerial'},
	{name:'operateDate'},
	{name:'ownerNo'},
	{name:'outstockType'},
	{name:'operateType'},
	{name:'pickType'},
	{name:'batchNo'},
	{name:'waveNo'},
	{name:'expType'},
	{name:'expNo'},
	{name:'custNo'},
	{name:'subCustNo'},
	{name:'articleNo'},
	{name:'articleId'},
	{name:'packingQty'},
	{name:'SCellNo'},
	{name:'SCellId'},
	{name:'SContainerNo'},
	{name:'DCellNo'},
	{name:'DCellId'},
	{name:'pickContainerNo'},
	{name:'custContainerNo'},
	{name:'articleQty'},
	{name:'locateQty'},
	{name:'status'},
	{name:'deliverArea'},
	{name:'lineNo'},
	{name:'priority'},
	{name:'ASorterChuteNo'},
	{name:'checkChuteNo'},
	{name:'deliverObj'},
	{name:'suppCount'},
	{name:'equipmentNo'},
	{name:'dpsCellNo'},
	{name:'tempStatus'},
	{name:'expDate'},
	{name:'stockType'},
	{name:'labelNo'},
	{name:'emptyFlag'},
	{name:'sourceType'},
	{name:'rgstName'},
	{name:'rgstDate'},
	{name:'updtName'},
	{name:'updtDate'},
	
	{name:'areaNo'},
	{name:'areaName'},
	{name:'ownerName'},
	{name:'custName'},
	{name:'subCustName'},
	{name:'articleName'},
	{name:'barcode'},
	{name:'produceDate'},
	{name:'sourceTypeText'},
	{name:'outstockTypeText'},
	{name:'expTypeText'},
	{name:'importBatchNo'},
	{name:'expireDate'},
	{name:'quality'},
	{name:'textQuality'},
	{name:'lotNo'},
	{name:'rsvBatch1'},
	{name:'rsvBatch2'},
	{name:'rsvBatch3'},
	{name:'rsvBatch4'},
	{name:'rsvBatch5'},
	{name:'rsvBatch6'},
	{name:'rsvBatch7'},
	{name:'rsvBatch8'},
	{name:'wareNo'},
	{name:'wareaNo'},//库区加储区
	{name:'ownerArticleNo'},
	{name:'flag'},
	{name:'industryFlag'},//行业标识；1：传统；2：电商 huangb 20160705
	{name:'isSengflag'},//是否可以发单;0-不可发单;1-可以发单 huangb 20160805
	//add by huangcx at 20160528
	{name:'qminOperatePacking'},
	{name:'unitPacking'},
	{name:'packingUnit'},
	{name:'packingUnitQmin'},
	{name:'Unit'},
	{name:'packingSpec'},
	{name:'packingSpecQmin'},
	{name:'spec'},
	//end add
	{name:'printFaceSheet'},
	{name:'printBuilt'},
	{name:'printInvoice'}
	
	
    ],
    idProperty:'warehouseNo,directSerial,operateDate'
});