Ext.define('cms.model.odata.odata_PackageDModel', {
    extend: 'Ext.data.Model',
    fields: [
	{name:'enterpriseNo'},
	{name:'warehouseNo'},
	{name:'ownerNo'},
	{name:'poNo'},
	{name:'sourceexpNo'},
	{name:'shipperDeliverNo'},
	{name:'ownerCustNo'},
	{name:'custNo'},
	{name:'subCustNo'},
	{name:'expDate'},
	{name:'statusText'},
	{name:'custAddress'},
	
	{name:'custAddressCode'},
	{name:'contactorName'},
	{name:'custPhone'},
	{name:'custMail'},
	{name:'remark'},
	{name:'printFlag'},
	{name:'cellNo'},
	{name:'containerNo'},
	{name:'shipperNo'},
	{name:'deliverAddress'},
	{name:'orgNo'},
	{name:'sendAddress'},
	
	{name:'sendAddressCode'},
	{name:'sendName'},
	{name:'sendCompanyName'},
	{name:'sendPostcode'},
	{name:'sendMobilePhone'},
	{name:'sendTelephone'},
	{name:'sendJpn'},
	{name:'sendProvince'},
	{name:'sendCity'},
	{name:'sendZone'},
	{name:'sendCountry'},
	{name:'receiveCompanyName'},
	
	{name:'receiveTelephone'},
	{name:'receiveJpn'},
	{name:'receiveProvince'},
	{name:'receiveCity'},
	{name:'receiveZone'},
	{name:'receiveCountry'},
	{name:'takeAddress'},
	{name:'takeAddressCode'},
	{name:'takeName'},
	{name:'takeCompanyName'},
	{name:'takePostcode'},
	{name:'takeMobilePhone'},
	
	{name:'takeTelephone'},
	{name:'takeJpn'},
	{name:'takeProvince'},
	{name:'takeCity'},
	{name:'takeZone'},
	{name:'takeCountry'},
	{name:'deliverdateType'},
	{name:'envoicePrintStatus'},
	{name:'waybillPrintStatus'},
	{name:'packlistPrintStatus'},
	{name:'rgstName'},
	{name:'rgstDate'},
	
	{name:'updtName'},
	{name:'updtDate'},
	{name:'instockName'},
	{name:'instockDate'},
	{name:'outstockName'},
	{name:'outstockDate'},
	{name:'statusText'},
	{name:'shipperName'},
	{name:'ownerName'}
	
 	],
    idProperty:'enterpriseNo,warehouseNo,poNo,sourceexpNo,shipperDeliverNo'
});