/**
 * 创建人:JUN
 */
Ext.define('cms.model.odata.odata_ExpMModel', {
    extend: 'Ext.data.Model',
    fields: [

        {name:'enterpriseNo'},
		{name:'warehouseNo'},
		{name:'expNo'},
		{name:'expType'},
		{name:'ownerNo'},
		{name:'ownerCustNo'},
		{name:'custNo'},
		{name:'subCustNo'},
	 	{name:'sourceexpType'},
	 	{name:'sourceexpNo'},
	 	{name:'expDate'},
	 	{name:'fastFlag'},
	 	{name:'status'},
	 	{name:'priority'},
	 	{name:'addExpNo'},
	 	{name:'importNo'},
	 	{name:'deliverType'},
	 	{name:'transportType'},
	 	{name:'batchNo'},
	 	{name:'lineNo'},
	 	{name:'fullLineName'},
	 	{name:'custAddress'},
	 	{name:'custAddressCode'},
	 	{name:'contactorName'},
	 	{name:'custPhone'},
	 	{name:'custMail'},
	 	{name:'errorStatus'},
	 	{name:'createFlag'},
	 	{name:'returnFlag'},
	 	{name:'expRemark'},
	 	{name:'belongFlag'},
	 	{name:'sendFlag'},
	 	{name:'bufferLineNo'},
	 	{name:'specialArticleGroup'},
	 	{name:'expStatus'},
	 	{name:'stockType'},
	 	{name:'orderPeriod'},
	 	{name:'financeType'},
	 	{name:'kickFlag'},
	 	{name:'realCustNo'},
	 	{name:'realCustName'},
	 	{name:'deptName'},
	 	{name:'agentNo'},
	 	{name:'paymentTerm'},
	 	{name:'deptNo'},
	 	{name:'custExpNo'},
	 	{name:'erpoperateDate'},
	 	{name:'custsendDate'},
	 	{name:'printFlag'},
	 	{name:'erpNo'},
	 	{name:'diffReason'},
	 	{name:'rgstName'},
	 	{name:'rgstDate'},
	 	{name:'updtName'},
	 	{name:'updtDate'},
	 	{name:'waveNo'},
	 	{name:'shipperNo'},
	 	{name:'shipperName'},
	 	
	 	{name:'custName'},
	 	{name:'custAlias'},
	 	{name:'articleItems'},
	 	{name:'totalQty'},
	 	{name:'totalVolumn'},
	 	{name:'sumVolumn'},
	 	{name:'sumWeight'},
	 	{name:'sumBoxQty'},
	 	{name:'statusText'},
	 	{name:'expNoCount'},
	 	{name:'shipperDeliverNo'},
		{name:'deliverAddress'},
		{name:'printBillFlag'},
		{name:'orderSource'},
		{name:'orgNo'},
	 	{name:'lineName'},
	 	{name:'ownerName'},
		{name:'takeType'},
		{name:'lastCustsendDate'},
		{name:'calculateCount'},
		{name:'custAddress'},
		{name:'custPhone1'},
		{name:'contactorName1'},
		///////////////////////////////////
		{name:'strRgstDate'},
		
	     {name:'reportUpSerial'},
	     {name:'shopNo'},
	     {name:'skucount'},
	     {name:'sendAddress'},
	     {name:'sendAddressCode'},
	     {name:'sendName'},
	     {name:'sendCompanyName'},
	     {name:'sendPostcode'},
	     {name:'sendMobilePhone'},
	     {name:'sendTelephone'},
	     {name:'sendJpn'},
	     {name:'sendProvince'},
	     {name:'sendCity'},
	     {name:'sendZone'},
	     {name:'sendCountry'},
	     {name:'receiveCompanyName'},
	     {name:'receiveTelephone'},
	     {name:'receiveJpn'},
	     {name:'receiveProvince'},
	     {name:'receiveCity'},
	     {name:'receiveZone'},
	     {name:'receiveCountry'},
	     {name:'takeAddress'},
	     {name:'takeAddressCode'},
	     {name:'takeName'},
	     {name:'takeCompanyName'},
	     {name:'takePostcode'},
	     {name:'takeMobilePhone'},
	     {name:'takeTelephone'},
	     {name:'takeJpn'},
	     {name:'takeProvince'},
	     {name:'takeCity'},
	     {name:'takeZone'},
	     {name:'takeCountry'}
    ],
    idProperty:'enterpriseNo,warehouseNo,expNo,expType'
});







