/**
 * 模块名称：计费公式管理Model
 * 模块编码：B101
 * 创建：chensr 
 */
Ext.define('cms.model.cost.cost_FormulasetModel', {
    extend: 'Ext.data.Model',
    idProperty:'enterpriseNo,warehouseNo,ownerNo,billingProject,billingType',
    fields: [
        {name:'enterpriseNo'},
		{name:'warehouseNo'},
		{name:'ownerNo'},
		{name:'billingProject'},
		{name:'projectName'},
		{name:'billingCycle'},
		{name:'billingFlag'},
		{name:'billingUnit'},	
		{name:'unitPrice'},
		{name:'appendCondition'},
		{name:'appendValue1'},
		{name:'appendValue2'},
		{name:'standardFlag'},
		{name:'otherCost1'},
		{name:'otherCost2'},
		{name:'otherCost3'},
		{name:'otherCost4'},
		{name:'otherCost5'},
		{name:'remark'},
		{name:'status'},
		{name:'statusText'},
		{name:'fixedValue'},
		{name:'valueFlag'},		
		{name:'rgstName'},
		{name:'rgstDate'},
		{name:'updtName'},
		{name:'updtDate'},
		{name:'billingCycleText'},
		{name:'billingFlagText'},
		{name:'billingUnitText'},
		{name:'appendConditionText'},
		{name:'projectText'},
		{name:'billingType'},
		{name:'billingTypeText'},
		{name:'billingTypeText'},
		{name:'familyNo'},
		{name:'familyText'},
		{name:'endDate'},
		{name:'balanceDay'},
		{name:'endDateText'},
		{name:'balanceDayText'},
		{name:'standardFlagText'},
		{name:'ownerNoText'},
		{name:'choiceFlag'},
		{name:'weekBalanceDay'},
		{name:'monthBalanceDay'},
		{name:'costFlag'},
		{name:'costFlagText'},
		{name:'beginDate'},
		{name:'beginDateText'}
    ]
});