/**
 *获取报损建单头档
 *创建：hkl
 */
Ext.define('cms.store.sodata.sodata_WasteMStore',{
	extend:'Ext.data.Store',
	model:'cms.model.sodata.sodata_WasteMModel',
	pageSize : appConfig.getPageSize(),
	storeId:'sodata_WasteMStore',
	autoLoad:false,
	proxy:{
		type:'ajax',
		method:'post',
		url:'sodata_WasteAction_getWaste_MList.action',
		reader:{
			root:'rootList',
			totalProperty:'totalCount'
		}
	}
});